// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 2CH2Ar4ka58N2cNnNntUTF
// Component: _GjGwxCnnc2N
import * as React from "react";
import {
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicImg as PlasmicImg__,
  PlasmicPageGuard as PlasmicPageGuard__,
  Stack as Stack__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  initializeCodeComponentStates,
  useCurrentUser,
  useDollarState
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv
} from "@plasmicapp/react-web/lib/host";
import * as plasmicAuth from "@plasmicapp/react-web/lib/auth";
import { usePlasmicDataSourceContext } from "@plasmicapp/data-sources-context";
import { usePlasmicDataOp } from "@plasmicapp/react-web/lib/data-sources";
import PageLayout from "../../PageLayout"; // plasmic-import: WnGguekajEU8/component
import DateTimeRangePicker from "../../DateTimeRangePicker"; // plasmic-import: BeO20828hgvb/component
import { AntdDatePicker } from "@plasmicpkgs/antd5/skinny/registerDatePicker";
import { datePickerHelpers as AntdDatePicker_Helpers } from "@plasmicpkgs/antd5/skinny/registerDatePicker";
import Statistic from "../../Statistic"; // plasmic-import: nZyKNWyFtYVu/component
import Chart from "../../Chart"; // plasmic-import: 2pmkJgbNAmBk/component
import Card from "../../Card"; // plasmic-import: J2HwTBpbSme2/component
import { useScreenVariants as useScreenVariantsb4PLyHj3O0M } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: b4pLY_hj3o0M/globalVariant
import "@plasmicapp/react-web/lib/plasmic.css";
import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import plasmic_plasmic_rich_components_css from "../plasmic_rich_components/plasmic.module.css"; // plasmic-import: jkU633o1Cz7HrJdwdxhVHk/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: 2CH2Ar4ka58N2cNnNntUTF/projectcss
import sty from "./PlasmicMonthOverview.module.css"; // plasmic-import: _GjGwxCnnc2N/css
import image7Lrlrx7JLcvmm from "./images/image7.svg"; // plasmic-import: Lrlrx7JLcvmm/picture
import orderIconWeRlvMh1ACg from "./images/orderIcon.svg"; // plasmic-import: weRlvMH1a-CG/picture
import dollarIcon9QlosHJqwWs from "./images/dollarIcon.svg"; // plasmic-import: -9qlosHJqwWs/picture
import cartIconDz53YaMa7D4 from "./images/cartIcon.svg"; // plasmic-import: Dz53ya_MA7d4/picture

createPlasmicElementProxy;

export const PlasmicMonthOverview__VariantProps = new Array();

export const PlasmicMonthOverview__ArgProps = new Array();

const $$ = {};

function PlasmicMonthOverview__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);
  const $props = {
    ...args,
    ...variants
  };
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const currentUser = useCurrentUser?.() || {};
  let [$queries, setDollarQueries] = React.useState({});
  const stateSpecs = React.useMemo(
    () => [
      {
        path: "start.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined,
        onMutate: generateOnMutateForSpec("value", AntdDatePicker_Helpers)
      }
    ],

    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: $queries,
    $refs
  });
  const new$Queries = {
    totalUsersByMonthCustomRange: usePlasmicDataOp(() => {
      return {
        sourceId: "aUJKGYUcLouK5WjQbDqTRv",
        opId: "454fcd2b-af91-4e71-abc1-a29ca53efc4d",
        userArgs: {
          query: [$state.start.value]
        },
        cacheKey: `plasmic.$.454fcd2b-af91-4e71-abc1-a29ca53efc4d.$.`,
        invalidatedKeys: null,
        roleId: null
      };
    }),
    totalOrdersByDateRange: usePlasmicDataOp(() => {
      return {
        sourceId: "aUJKGYUcLouK5WjQbDqTRv",
        opId: "7bc32e9e-1cca-4047-a006-30c1d899ad78",
        userArgs: {
          query: [$state.start.value, $state.start.value]
        },
        cacheKey: `plasmic.$.7bc32e9e-1cca-4047-a006-30c1d899ad78.$.`,
        invalidatedKeys: null,
        roleId: null
      };
    }),
    currentRevenue: usePlasmicDataOp(() => {
      return {
        sourceId: "aUJKGYUcLouK5WjQbDqTRv",
        opId: "207b8591-70b4-4031-8a20-bb62a525df3c",
        userArgs: {
          query: [$state.start.value, $state.start.value]
        },
        cacheKey: `plasmic.$.207b8591-70b4-4031-8a20-bb62a525df3c.$.`,
        invalidatedKeys: null,
        roleId: null
      };
    }),
    currentTotalCustomers: usePlasmicDataOp(() => {
      return {
        sourceId: "aUJKGYUcLouK5WjQbDqTRv",
        opId: "b53b87b6-54f4-44b9-9929-d8168f592870",
        userArgs: {},
        cacheKey: `plasmic.$.b53b87b6-54f4-44b9-9929-d8168f592870.$.`,
        invalidatedKeys: null,
        roleId: null
      };
    }),
    _12MonthRevenue: usePlasmicDataOp(() => {
      return {
        sourceId: "aUJKGYUcLouK5WjQbDqTRv",
        opId: "058ff472-fbba-40eb-8286-855e3759aab6",
        userArgs: {
          query: [$state.start.value]
        },
        cacheKey: `plasmic.$.058ff472-fbba-40eb-8286-855e3759aab6.$.`,
        invalidatedKeys: null,
        roleId: null
      };
    }),
    moMUserGrowth: usePlasmicDataOp(() => {
      return {
        sourceId: "aUJKGYUcLouK5WjQbDqTRv",
        opId: "3c8cff5a-db8f-4097-86f5-cebadc6b7e92",
        userArgs: {
          query: [
            $state.start.value,
            $state.start.value,
            $state.start.value,
            $state.start.value
          ]
        },
        cacheKey: `plasmic.$.3c8cff5a-db8f-4097-86f5-cebadc6b7e92.$.`,
        invalidatedKeys: null,
        roleId: null
      };
    }),
    moMOrderGrowth: usePlasmicDataOp(() => {
      return {
        sourceId: "aUJKGYUcLouK5WjQbDqTRv",
        opId: "af7bee78-1a04-4ec9-b9ea-f0343446e46a",
        userArgs: {
          query: [
            $state.start.value,
            $state.start.value,
            $state.start.value,
            $state.start.value
          ]
        },
        cacheKey: `plasmic.$.af7bee78-1a04-4ec9-b9ea-f0343446e46a.$.`,
        invalidatedKeys: null,
        roleId: null
      };
    }),
    moMAvgOrderGrowth: usePlasmicDataOp(() => {
      return {
        sourceId: "aUJKGYUcLouK5WjQbDqTRv",
        opId: "a59bcc93-427f-4baf-a744-302d6ec4b7da",
        userArgs: {
          query: [
            $state.start.value,
            $state.start.value,
            $state.start.value,
            $state.start.value
          ]
        },
        cacheKey: `plasmic.$.a59bcc93-427f-4baf-a744-302d6ec4b7da.$.`,
        invalidatedKeys: null,
        roleId: null
      };
    }),
    moMRevenueGrowth: usePlasmicDataOp(() => {
      return {
        sourceId: "aUJKGYUcLouK5WjQbDqTRv",
        opId: "9cb5ac3d-98d4-4e3c-b97c-7204542a3b9f",
        userArgs: {
          query: [
            $state.start.value,
            $state.start.value,
            $state.start.value,
            $state.start.value
          ]
        },
        cacheKey: `plasmic.$.9cb5ac3d-98d4-4e3c-b97c-7204542a3b9f.$.`,
        invalidatedKeys: null,
        roleId: null
      };
    }),
    currentAvgOrder: usePlasmicDataOp(() => {
      return {
        sourceId: "aUJKGYUcLouK5WjQbDqTRv",
        opId: "3222fac4-06f4-4ba0-a67f-01d832b0d14d",
        userArgs: {
          query: [$state.start.value, $state.start.value]
        },
        cacheKey: `plasmic.$.3222fac4-06f4-4ba0-a67f-01d832b0d14d.$.`,
        invalidatedKeys: null,
        roleId: null
      };
    }),
    topCountriesByRevenue: usePlasmicDataOp(() => {
      return {
        sourceId: "aUJKGYUcLouK5WjQbDqTRv",
        opId: "03822377-8a53-409e-ad43-cc84f92ec24c",
        userArgs: {},
        cacheKey: `plasmic.$.03822377-8a53-409e-ad43-cc84f92ec24c.$.`,
        invalidatedKeys: null,
        roleId: null
      };
    }),
    topProductsByQuantitySold: usePlasmicDataOp(() => {
      return {
        sourceId: "aUJKGYUcLouK5WjQbDqTRv",
        opId: "99c06339-9ede-441f-a9ea-82f54ddf4a58",
        userArgs: {
          query: [$state.start.value, $state.start.value]
        },
        cacheKey: `plasmic.$.99c06339-9ede-441f-a9ea-82f54ddf4a58.$.`,
        invalidatedKeys: null,
        roleId: null
      };
    }),
    totalProductsSold: usePlasmicDataOp(() => {
      return {
        sourceId: "aUJKGYUcLouK5WjQbDqTRv",
        opId: "8592ed19-6ea9-4101-bf62-7705e9180b52",
        userArgs: {},
        cacheKey: `plasmic.$.8592ed19-6ea9-4101-bf62-7705e9180b52.$.`,
        invalidatedKeys: null,
        roleId: null
      };
    }),
    topCategoriesByOrders: usePlasmicDataOp(() => {
      return {
        sourceId: "aUJKGYUcLouK5WjQbDqTRv",
        opId: "cf811e9e-0104-401b-9894-d32ff6723148",
        userArgs: {
          query: [
            $state.start.value,
            $state.start.value,
            $state.start.value,
            $state.start.value
          ]
        },
        cacheKey: `plasmic.$.cf811e9e-0104-401b-9894-d32ff6723148.$.`,
        invalidatedKeys: null,
        roleId: null
      };
    })
  };
  if (Object.keys(new$Queries).some(k => new$Queries[k] !== $queries[k])) {
    setDollarQueries(new$Queries);
    $queries = new$Queries;
  }
  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantsb4PLyHj3O0M()
  });
  return (
    <React.Fragment>
      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            plasmic_antd_5_hostless_css.plasmic_tokens,
            plasmic_plasmic_rich_components_css.plasmic_tokens,
            sty.root
          )}
        >
          <PageLayout
            data-plasmic-name={"pageLayout"}
            data-plasmic-override={overrides.pageLayout}
            className={classNames("__wab_instance", sty.pageLayout)}
          >
            <DataCtxReader__>
              {$ctx => (
                <React.Fragment>
                  <section
                    className={classNames(projectcss.all, sty.section__inH46)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__jqSqX)}
                    >
                      <h1
                        data-plasmic-name={"h1"}
                        data-plasmic-override={overrides.h1}
                        className={classNames(
                          projectcss.all,
                          projectcss.h1,
                          projectcss.__wab_text,
                          sty.h1
                        )}
                      >
                        {"Welcome back! "}
                      </h1>
                    </div>
                  </section>
                  <section
                    className={classNames(projectcss.all, sty.section__ygOkv)}
                  >
                    <DateTimeRangePicker
                      data-plasmic-name={"dateTimeRangePicker"}
                      data-plasmic-override={overrides.dateTimeRangePicker}
                      className={classNames(
                        "__wab_instance",
                        sty.dateTimeRangePicker
                      )}
                    >
                      {(() => {
                        const child$Props = {
                          allowClear: true,
                          bordered: true,
                          className: classNames("__wab_instance", sty.start),
                          onChange: generateStateOnChangePropForCodeComponents(
                            $state,
                            "value",
                            ["start", "value"],
                            AntdDatePicker_Helpers
                          ),
                          picker: "date",
                          popupScopeClassName: sty["start__datePickerPopup"],
                          showTime: false,
                          value: generateStateValueProp($state, [
                            "start",
                            "value"
                          ])
                        };
                        initializeCodeComponentStates(
                          $state,
                          [
                            {
                              name: "value",
                              plasmicStateName: "start.value"
                            }
                          ],

                          [],
                          AntdDatePicker_Helpers ?? {},
                          child$Props
                        );
                        return (
                          <AntdDatePicker
                            data-plasmic-name={"start"}
                            data-plasmic-override={overrides.start}
                            {...child$Props}
                          />
                        );
                      })()}
                    </DateTimeRangePicker>
                    <Stack__
                      as={"div"}
                      hasGap={true}
                      className={classNames(
                        projectcss.all,
                        sty.freeBox___1Er2A
                      )}
                    >
                      <Statistic
                        className={classNames(
                          "__wab_instance",
                          sty.statistic__zc1Bi
                        )}
                        number={
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__sNqbY
                            )}
                          >
                            <React.Fragment>
                              <React.Fragment>{""}</React.Fragment>
                              {
                                <h2
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.h2,
                                    projectcss.__wab_text,
                                    sty.h2__iwU7Q
                                  )}
                                >
                                  <React.Fragment>
                                    {(() => {
                                      try {
                                        return $queries
                                          .totalUsersByMonthCustomRange.data[0]
                                          .cumulative_users;
                                      } catch (e) {
                                        if (
                                          e instanceof TypeError ||
                                          e?.plasmicType ===
                                            "PlasmicUndefinedDataError"
                                        ) {
                                          return "NULL";
                                        }
                                        throw e;
                                      }
                                    })()}
                                  </React.Fragment>
                                </h2>
                              }

                              <React.Fragment>{""}</React.Fragment>
                            </React.Fragment>
                          </div>
                        }
                        numberTrend={
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__mxhKn
                            )}
                            style={(() => {
                              try {
                                return (() => {
                                  function decimalToPercentage(decimalValue) {
                                    const percentage = Math.floor(
                                      decimalValue * 1
                                    );
                                    return percentage;
                                  }
                                  const usersIncreasePercentage =
                                    $queries.moMUserGrowth.data[0]
                                      .user_increase_percentage;
                                  const displayText =
                                    decimalToPercentage(
                                      usersIncreasePercentage
                                    ) < 0
                                      ? {
                                          color:
                                            "var(--plasmic-token-danger-800)",
                                          backgroundColor:
                                            "var(--plasmic-token-danger-100)"
                                        }
                                      : {};
                                  return displayText;
                                })();
                              } catch (e) {
                                if (
                                  e instanceof TypeError ||
                                  e?.plasmicType === "PlasmicUndefinedDataError"
                                ) {
                                  return undefined;
                                }
                                throw e;
                              }
                            })()}
                          >
                            <React.Fragment>
                              {(() => {
                                try {
                                  return (() => {
                                    function decimalToPercentage(decimalValue) {
                                      const percentage = Math.floor(
                                        decimalValue * 1
                                      );
                                      return percentage + "%";
                                    }
                                    const userIncreasePercentage =
                                      $queries.moMUserGrowth.data[0]
                                        .user_increase_percentage;
                                    const displayText = decimalToPercentage(
                                      userIncreasePercentage
                                    );
                                    return displayText;
                                  })();
                                } catch (e) {
                                  if (
                                    e instanceof TypeError ||
                                    e?.plasmicType ===
                                      "PlasmicUndefinedDataError"
                                  ) {
                                    return "NULL";
                                  }
                                  throw e;
                                }
                              })()}
                            </React.Fragment>
                          </div>
                        }
                        timeRange={"from last month"}
                        unit={
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__rKaFy
                            )}
                          >
                            <p
                              className={classNames(
                                projectcss.all,
                                projectcss.p,
                                projectcss.__wab_text,
                                sty.p__m03X4
                              )}
                            >
                              {"Total users"}
                            </p>
                            <PlasmicImg__
                              alt={""}
                              className={classNames(sty.img__eJmKs)}
                              displayHeight={"auto"}
                              displayMaxHeight={"28px"}
                              displayMaxWidth={"28px"}
                              displayMinHeight={"0"}
                              displayMinWidth={"0"}
                              displayWidth={"auto"}
                              loading={"lazy"}
                              src={{
                                src: image7Lrlrx7JLcvmm,
                                fullWidth: 150,
                                fullHeight: 150,
                                aspectRatio: 1
                              }}
                            />
                          </div>
                        }
                      />

                      <Statistic
                        className={classNames(
                          "__wab_instance",
                          sty.statistic__rQlr3
                        )}
                        number={
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__tIryY
                            )}
                          >
                            <React.Fragment>
                              <React.Fragment>{""}</React.Fragment>
                              {
                                <h2
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.h2,
                                    projectcss.__wab_text,
                                    sty.h2__ykzfr
                                  )}
                                >
                                  <React.Fragment>
                                    {(() => {
                                      try {
                                        return $queries.totalOrdersByDateRange
                                          .data[0].order_count;
                                      } catch (e) {
                                        if (
                                          e instanceof TypeError ||
                                          e?.plasmicType ===
                                            "PlasmicUndefinedDataError"
                                        ) {
                                          return "NULL";
                                        }
                                        throw e;
                                      }
                                    })()}
                                  </React.Fragment>
                                </h2>
                              }

                              <React.Fragment>{""}</React.Fragment>
                            </React.Fragment>
                          </div>
                        }
                        numberTrend={
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__rjBUq
                            )}
                            style={(() => {
                              try {
                                return (() => {
                                  function decimalToPercentage(decimalValue) {
                                    const percentage = Math.floor(
                                      decimalValue * 1
                                    );
                                    return percentage;
                                  }
                                  const ordersIncreasePercentage =
                                    $queries.moMOrderGrowth.data[0]
                                      .order_increase_percentage;
                                  const displayText =
                                    decimalToPercentage(
                                      ordersIncreasePercentage
                                    ) < 0
                                      ? {
                                          color:
                                            "var(--plasmic-token-danger-800)",
                                          backgroundColor:
                                            "var(--plasmic-token-danger-100)"
                                        }
                                      : {};
                                  return displayText;
                                })();
                              } catch (e) {
                                if (
                                  e instanceof TypeError ||
                                  e?.plasmicType === "PlasmicUndefinedDataError"
                                ) {
                                  return undefined;
                                }
                                throw e;
                              }
                            })()}
                          >
                            <React.Fragment>
                              {(() => {
                                try {
                                  return (() => {
                                    function decimalToPercentage(decimalValue) {
                                      const percentage = Math.floor(
                                        decimalValue * 1
                                      );
                                      return percentage + "%";
                                    }
                                    const ordersIncreasePercentage =
                                      $queries.moMOrderGrowth.data[0]
                                        .order_increase_percentage;
                                    const displayText = decimalToPercentage(
                                      ordersIncreasePercentage
                                    );
                                    return displayText;
                                  })();
                                } catch (e) {
                                  if (
                                    e instanceof TypeError ||
                                    e?.plasmicType ===
                                      "PlasmicUndefinedDataError"
                                  ) {
                                    return "NULL";
                                  }
                                  throw e;
                                }
                              })()}
                            </React.Fragment>
                          </div>
                        }
                        unit={
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__xc51T
                            )}
                          >
                            <p
                              className={classNames(
                                projectcss.all,
                                projectcss.p,
                                projectcss.__wab_text,
                                sty.p__uLkPn
                              )}
                            >
                              {"New orders"}
                            </p>
                            <PlasmicImg__
                              alt={""}
                              className={classNames(sty.img___5BcZ2)}
                              displayHeight={"auto"}
                              displayMaxHeight={"28px"}
                              displayMaxWidth={"28px"}
                              displayMinHeight={"0"}
                              displayMinWidth={"0"}
                              displayWidth={"auto"}
                              loading={"lazy"}
                              src={{
                                src: orderIconWeRlvMh1ACg,
                                fullWidth: 150,
                                fullHeight: 150,
                                aspectRatio: 1
                              }}
                            />
                          </div>
                        }
                      />

                      <Statistic
                        className={classNames(
                          "__wab_instance",
                          sty.statistic___6Sg2E
                        )}
                        number={
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__iTpV
                            )}
                          >
                            <React.Fragment>
                              <React.Fragment>{""}</React.Fragment>
                              {
                                <h2
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.h2,
                                    projectcss.__wab_text,
                                    sty.h2__cnOyH
                                  )}
                                >
                                  <React.Fragment>
                                    {(() => {
                                      try {
                                        return (
                                          "$" +
                                          Intl.NumberFormat("en").format(
                                            $queries.currentAvgOrder.data[0]
                                              .avg_order_total
                                          )
                                        );
                                      } catch (e) {
                                        if (
                                          e instanceof TypeError ||
                                          e?.plasmicType ===
                                            "PlasmicUndefinedDataError"
                                        ) {
                                          return "NULL";
                                        }
                                        throw e;
                                      }
                                    })()}
                                  </React.Fragment>
                                </h2>
                              }

                              <React.Fragment>{""}</React.Fragment>
                            </React.Fragment>
                          </div>
                        }
                        numberTrend={
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__dZrTd
                            )}
                            style={(() => {
                              try {
                                return (() => {
                                  function decimalToPercentage(decimalValue) {
                                    const percentage = Math.floor(
                                      decimalValue * 1
                                    );
                                    return percentage;
                                  }
                                  const avg_order_value_increase_percentage =
                                    $queries.moMAvgOrderGrowth.data[0]
                                      .avg_order_value_increase_percentage;
                                  const displayText =
                                    decimalToPercentage(
                                      avg_order_value_increase_percentage
                                    ) < 0
                                      ? {
                                          color:
                                            "var(--plasmic-token-danger-800)",
                                          backgroundColor:
                                            "var(--plasmic-token-danger-100)"
                                        }
                                      : {};
                                  return displayText;
                                })();
                              } catch (e) {
                                if (
                                  e instanceof TypeError ||
                                  e?.plasmicType === "PlasmicUndefinedDataError"
                                ) {
                                  return undefined;
                                }
                                throw e;
                              }
                            })()}
                          >
                            <React.Fragment>
                              {(() => {
                                try {
                                  return (() => {
                                    function decimalToPercentage(decimalValue) {
                                      const percentage = Math.floor(
                                        decimalValue * 1
                                      );
                                      return percentage + "%";
                                    }
                                    const avg_order_value_increase_percentage =
                                      $queries.moMAvgOrderGrowth.data[0]
                                        .avg_order_value_increase_percentage;
                                    const displayText = decimalToPercentage(
                                      avg_order_value_increase_percentage
                                    );
                                    return displayText;
                                  })();
                                } catch (e) {
                                  if (
                                    e instanceof TypeError ||
                                    e?.plasmicType ===
                                      "PlasmicUndefinedDataError"
                                  ) {
                                    return "NULL";
                                  }
                                  throw e;
                                }
                              })()}
                            </React.Fragment>
                          </div>
                        }
                        unit={
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__yRaLy
                            )}
                          >
                            <p
                              className={classNames(
                                projectcss.all,
                                projectcss.p,
                                projectcss.__wab_text,
                                sty.p__glK2
                              )}
                            >
                              {"Avg. order value"}
                            </p>
                            <PlasmicImg__
                              alt={""}
                              className={classNames(sty.img__ipQkr)}
                              displayHeight={"auto"}
                              displayMaxHeight={"28px"}
                              displayMaxWidth={"28px"}
                              displayMinHeight={"0"}
                              displayMinWidth={"0"}
                              displayWidth={"auto"}
                              loading={"lazy"}
                              src={{
                                src: dollarIcon9QlosHJqwWs,
                                fullWidth: 150,
                                fullHeight: 150,
                                aspectRatio: 1
                              }}
                            />
                          </div>
                        }
                      />

                      <Statistic
                        className={classNames(
                          "__wab_instance",
                          sty.statistic__nkCtA
                        )}
                        number={
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__weqoh
                            )}
                          >
                            <React.Fragment>
                              <React.Fragment>{""}</React.Fragment>
                              {
                                <h2
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.h2,
                                    projectcss.__wab_text,
                                    sty.h2__qUgN
                                  )}
                                >
                                  <React.Fragment>
                                    {(() => {
                                      try {
                                        return (
                                          "$" +
                                          Intl.NumberFormat("en").format(
                                            $queries.currentRevenue.data[0]
                                              .total_revenue_this_month
                                          )
                                        );
                                      } catch (e) {
                                        if (
                                          e instanceof TypeError ||
                                          e?.plasmicType ===
                                            "PlasmicUndefinedDataError"
                                        ) {
                                          return "NULL";
                                        }
                                        throw e;
                                      }
                                    })()}
                                  </React.Fragment>
                                </h2>
                              }

                              <React.Fragment>{""}</React.Fragment>
                            </React.Fragment>
                          </div>
                        }
                        numberTrend={
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__kS17A
                            )}
                            style={(() => {
                              try {
                                return (() => {
                                  function decimalToPercentage(decimalValue) {
                                    const percentage = Math.floor(
                                      decimalValue * 1
                                    );
                                    return percentage;
                                  }
                                  const revenueIncreasePercentage =
                                    $queries.moMRevenueGrowth.data[0]
                                      .revenue_increase_percentage;
                                  const displayText =
                                    decimalToPercentage(
                                      revenueIncreasePercentage
                                    ) < 0
                                      ? {
                                          color:
                                            "var(--plasmic-token-danger-800)",
                                          backgroundColor:
                                            "var(--plasmic-token-danger-100)"
                                        }
                                      : {};
                                  return displayText;
                                })();
                              } catch (e) {
                                if (
                                  e instanceof TypeError ||
                                  e?.plasmicType === "PlasmicUndefinedDataError"
                                ) {
                                  return undefined;
                                }
                                throw e;
                              }
                            })()}
                          >
                            <React.Fragment>
                              {(() => {
                                try {
                                  return (() => {
                                    function decimalToPercentage(decimalValue) {
                                      const percentage = Math.floor(
                                        decimalValue * 1
                                      );
                                      return percentage + "%";
                                    }
                                    const revenueIncreasePercentage =
                                      $queries.moMRevenueGrowth.data[0]
                                        .revenue_increase_percentage;
                                    const displayText = decimalToPercentage(
                                      revenueIncreasePercentage
                                    );
                                    return displayText;
                                  })();
                                } catch (e) {
                                  if (
                                    e instanceof TypeError ||
                                    e?.plasmicType ===
                                      "PlasmicUndefinedDataError"
                                  ) {
                                    return "NULL";
                                  }
                                  throw e;
                                }
                              })()}
                            </React.Fragment>
                          </div>
                        }
                        unit={
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__saC
                            )}
                          >
                            <p
                              className={classNames(
                                projectcss.all,
                                projectcss.p,
                                projectcss.__wab_text,
                                sty.p__lKkQ4
                              )}
                            >
                              {"Total revenue"}
                            </p>
                            <PlasmicImg__
                              alt={""}
                              className={classNames(sty.img___3EgQy)}
                              displayHeight={"auto"}
                              displayMaxHeight={"28px"}
                              displayMaxWidth={"28px"}
                              displayMinHeight={"0"}
                              displayMinWidth={"0"}
                              displayWidth={"auto"}
                              loading={"lazy"}
                              src={{
                                src: cartIconDz53YaMa7D4,
                                fullWidth: 150,
                                fullHeight: 150,
                                aspectRatio: 1
                              }}
                            />
                          </div>
                        }
                      />
                    </Stack__>
                  </section>
                  <section
                    className={classNames(projectcss.all, sty.section__nx9Qk)}
                  >
                    <Chart
                      data-plasmic-name={"chart"}
                      data-plasmic-override={overrides.chart}
                      className={classNames("__wab_instance", sty.chart)}
                      get12MoRevenue={$queries._12MonthRevenue}
                    />
                  </section>
                  <section
                    className={classNames(projectcss.all, sty.section__cq9Zu)}
                  >
                    <Stack__
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.freeBox__spKy)}
                    >
                      <Card
                        className={classNames(
                          "__wab_instance",
                          sty.card__woXah
                        )}
                        title={
                          <h2
                            className={classNames(
                              projectcss.all,
                              projectcss.h2,
                              projectcss.__wab_text,
                              sty.h2___5935J
                            )}
                          >
                            {"Top products sold"}
                          </h2>
                        }
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__i74X7
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__diaK
                            )}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__qKd3F
                              )}
                            >
                              <React.Fragment>
                                {(() => {
                                  try {
                                    return undefined;
                                  } catch (e) {
                                    if (
                                      e instanceof TypeError ||
                                      e?.plasmicType ===
                                        "PlasmicUndefinedDataError"
                                    ) {
                                      return "Total users";
                                    }
                                    throw e;
                                  }
                                })()}
                              </React.Fragment>
                            </div>
                          </div>
                          {(_par =>
                            !_par ? [] : Array.isArray(_par) ? _par : [_par])(
                            (() => {
                              try {
                                return $queries.topProductsByQuantitySold.data;
                              } catch (e) {
                                if (
                                  e instanceof TypeError ||
                                  e?.plasmicType === "PlasmicUndefinedDataError"
                                ) {
                                  return [];
                                }
                                throw e;
                              }
                            })()
                          ).map((__plasmic_item_0, __plasmic_idx_0) => {
                            const currentItem = __plasmic_item_0;
                            const currentIndex = __plasmic_idx_0;
                            return (
                              <div
                                className={classNames(
                                  projectcss.all,
                                  sty.freeBox__sOnjw
                                )}
                                key={currentIndex}
                              >
                                <div
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.__wab_text,
                                    sty.text__dMhGt
                                  )}
                                >
                                  <React.Fragment>
                                    {(() => {
                                      try {
                                        return currentItem.product_name;
                                      } catch (e) {
                                        if (
                                          e instanceof TypeError ||
                                          e?.plasmicType ===
                                            "PlasmicUndefinedDataError"
                                        ) {
                                          return "Product ";
                                        }
                                        throw e;
                                      }
                                    })()}
                                  </React.Fragment>
                                </div>
                                <div
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.__wab_text,
                                    sty.text__rnPiF
                                  )}
                                >
                                  <React.Fragment>
                                    {(() => {
                                      try {
                                        return currentItem.total_quantity_sold;
                                      } catch (e) {
                                        if (
                                          e instanceof TypeError ||
                                          e?.plasmicType ===
                                            "PlasmicUndefinedDataError"
                                        ) {
                                          return "Revenue";
                                        }
                                        throw e;
                                      }
                                    })()}
                                  </React.Fragment>
                                </div>
                              </div>
                            );
                          })}
                        </div>
                      </Card>
                      <Card
                        className={classNames("__wab_instance", sty.card__hSPn)}
                        title={
                          <h2
                            className={classNames(
                              projectcss.all,
                              projectcss.h2,
                              projectcss.__wab_text,
                              sty.h2__fsknq
                            )}
                          >
                            {"Top product categories"}
                          </h2>
                        }
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__fF26O
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__jMiy0
                            )}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__gowd
                              )}
                            >
                              <React.Fragment>
                                {(() => {
                                  try {
                                    return undefined;
                                  } catch (e) {
                                    if (
                                      e instanceof TypeError ||
                                      e?.plasmicType ===
                                        "PlasmicUndefinedDataError"
                                    ) {
                                      return "Total users";
                                    }
                                    throw e;
                                  }
                                })()}
                              </React.Fragment>
                            </div>
                          </div>
                          {(_par =>
                            !_par ? [] : Array.isArray(_par) ? _par : [_par])(
                            (() => {
                              try {
                                return $queries.topCategoriesByOrders.data;
                              } catch (e) {
                                if (
                                  e instanceof TypeError ||
                                  e?.plasmicType === "PlasmicUndefinedDataError"
                                ) {
                                  return [];
                                }
                                throw e;
                              }
                            })()
                          ).map((__plasmic_item_0, __plasmic_idx_0) => {
                            const currentItem = __plasmic_item_0;
                            const currentIndex = __plasmic_idx_0;
                            return (
                              <div
                                className={classNames(
                                  projectcss.all,
                                  sty.freeBox__zJsvs
                                )}
                                key={currentIndex}
                              >
                                <div
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.__wab_text,
                                    sty.text__sBrI5
                                  )}
                                >
                                  <React.Fragment>
                                    {(() => {
                                      try {
                                        return currentItem.category_name;
                                      } catch (e) {
                                        if (
                                          e instanceof TypeError ||
                                          e?.plasmicType ===
                                            "PlasmicUndefinedDataError"
                                        ) {
                                          return "Product ";
                                        }
                                        throw e;
                                      }
                                    })()}
                                  </React.Fragment>
                                </div>
                                <div
                                  className={classNames(
                                    projectcss.all,
                                    projectcss.__wab_text,
                                    sty.text__ygS1U
                                  )}
                                >
                                  <React.Fragment>
                                    {(() => {
                                      try {
                                        return currentItem.num_orders_in_category;
                                      } catch (e) {
                                        if (
                                          e instanceof TypeError ||
                                          e?.plasmicType ===
                                            "PlasmicUndefinedDataError"
                                        ) {
                                          return "Revenue";
                                        }
                                        throw e;
                                      }
                                    })()}
                                  </React.Fragment>
                                </div>
                              </div>
                            );
                          })}
                        </div>
                      </Card>
                    </Stack__>
                  </section>
                </React.Fragment>
              )}
            </DataCtxReader__>
          </PageLayout>
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: ["root", "pageLayout", "h1", "dateTimeRangePicker", "start", "chart"],
  pageLayout: ["pageLayout", "h1", "dateTimeRangePicker", "start", "chart"],
  h1: ["h1"],
  dateTimeRangePicker: ["dateTimeRangePicker", "start"],
  start: ["start"],
  chart: ["chart"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicMonthOverview__ArgProps,
          internalVariantPropNames: PlasmicMonthOverview__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicMonthOverview__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicMonthOverview";
  } else {
    func.displayName = `PlasmicMonthOverview.${nodeName}`;
  }
  return func;
}

function withPlasmicPageGuard(WrappedComponent) {
  const PageGuard = props => (
    <PlasmicPageGuard__
      minRole={null}
      appId={"2CH2Ar4ka58N2cNnNntUTF"}
      authorizeEndpoint={"https://studio.plasmic.app/authorize"}
      canTriggerLogin={true}
    >
      <WrappedComponent {...props} />
    </PlasmicPageGuard__>
  );

  return PageGuard;
}

function withUsePlasmicAuth(WrappedComponent) {
  const WithUsePlasmicAuthComponent = props => {
    const dataSourceCtx = usePlasmicDataSourceContext() ?? {};
    const { isUserLoading, user, token } = plasmicAuth.usePlasmicAuth({
      appId: "2CH2Ar4ka58N2cNnNntUTF"
    });
    return (
      <PlasmicDataSourceContextProvider__
        value={{
          ...dataSourceCtx,
          isUserLoading,
          userAuthToken: token,
          user
        }}
      >
        <WrappedComponent {...props} />
      </PlasmicDataSourceContextProvider__>
    );
  };
  return WithUsePlasmicAuthComponent;
}

export const PlasmicMonthOverview = Object.assign(
  // Top-level PlasmicMonthOverview renders the root element
  withUsePlasmicAuth(withPlasmicPageGuard(makeNodeComponent("root"))),
  {
    // Helper components rendering sub-elements
    pageLayout: makeNodeComponent("pageLayout"),
    h1: makeNodeComponent("h1"),
    dateTimeRangePicker: makeNodeComponent("dateTimeRangePicker"),
    start: makeNodeComponent("start"),
    chart: makeNodeComponent("chart"),
    // Metadata about props expected for PlasmicMonthOverview
    internalVariantProps: PlasmicMonthOverview__VariantProps,
    internalArgProps: PlasmicMonthOverview__ArgProps,
    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicMonthOverview;
/* prettier-ignore-end */
